language: ruby
rvm:
  - 1.9.2
  - 1.9.3

gemfile:
  - ./gemfiles/Gemfile.chef.0.10.10
  - ./gemfiles/Gemfile.chef.10.12.0
  - ./gemfiles/Gemfile.chef.10.14.0
  - ./gemfiles/Gemfile.chef.10.16.0
  - ./gemfiles/Gemfile.chef.11.6.2
  - ./gemfiles/Gemfile.chef.11.8.0
  - ./gemfiles/Gemfile.chef.11.8.2
